### ISSUE TITLE
File upload with other string error

### ISSUE THREAD

**Issue by nowfalsalahudeen** [jaychang0917/SimpleApiClient#7]
Can you give me a nexample of how to upload a image with other strings like email,name,age etc..
i tried a lot ..failed..please

**Comment by jaychang0917** [comment]
I found that currently retrofit2 doesn't support custom converter for `MultiPart`, so if you want to upload file with other strings, you should use the `MultipartBody.Part` and `RequestBody`, *DON'T* use `@Body @MultiPart`. [example](https://stackoverflow.com/questions/39953457/how-to-upload-image-file-in-retrofit-2)

**Comment by nowfalsalahudeen** [comment]
k thank you..i just use retrofit things
