### ISSUE TITLE
Feedback gradle error

### ISSUE THREAD

**Issue by tcqq** [jaychang0917/SimpleApiClient#8]
When rebuild gradle, the following error occurs: 
```
Folder E:\GitHub\SimpleApiClient\app\build\generated\source\kaptKotlin\debug
Folder E:\GitHub\SimpleApiClient\app\build\generated\source\kaptKotlin\release
3rd-party Gradle plug-ins may be the cause

```
![image](https://user-images.githubusercontent.com/10644057/39677397-b6436a18-51ac-11e8-873d-9540f052e770.png)

When I remove `apply plugin: 'kotlin-android'`, the error will not appear.

**Comment by jaychang0917** [comment]
It is an android studio [issue](https://issuetracker.google.com/issues/74537216).

**Comment by tcqq** [comment]
Ok, thanks.
